# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2.1


defaults: &defaults
  resource_class: small
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.19.0

commands:
  npm_install:
    description: 'Install NPM Dependencies'
    steps:
      - run: npm i
      - save_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  restore_npm_cache:
    description: 'Restore NPM Cached Dependencies'
    steps:
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - npm-dependencies-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_npm_cache
      - npm_install
      - persist_to_workspace:
          root: ~/repo
          paths: .
  lint-and-test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run Unit Tests
          command: npm run test
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo -e "//npm.pkg.github.com/:_authToken=$GIT_TOKEN\nregistry=https://npm.pkg.github.com/swoopin-green" > ~/repo/dist/packages/gatsby-plugin/.npmrc
      - run:
          name: Publish package
          command: cd dist/packages/gatsby-plugin && npm publish

workflows:
  version: 2.1
  workflow:
    jobs:
      - install
      - lint-and-test:
          requires:
            - install
      - build:
          requires:
            - lint-and-test
      - deploy:
          requires:
            - build
          context:
            - swoopin
